# Generated by Django 6.0 on 2026-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_submission_answers_alter_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.JSONField(default=list),
        ),
    ]
