# Generated by Django 6.0 on 2026-01-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_submission_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='question',
            new_name='questions',
        ),
    ]
