# Generated by Django 6.0 on 2026-01-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_question_submission_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='questions',
        ),
    ]
