# Generated by Django 6.0 on 2026-01-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_submission_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expected_answer',
            field=models.JSONField(),
        ),
    ]
